### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by ryancoolround** [PaimonQwQ/L4D2-Plugins#3]
I was [informed of problems](https://ip-gamers.net/topic/2955-free-camera-for-fortnite-emotes-extension/#comment-12283) with compilation on SM 1.11.
//// free_camera.sp
//
// D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(237) : error 105: cannot find method or property "Cookie.GetInt"
// D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(238) : error 105: cannot find method or property "Cookie.GetInt"
// D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(239) : error 105: cannot find method or property "Cookie.GetFloat"
// D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(306) : error 105: cannot find method or property "Cookie.SetInt"
// D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(316) : error 105: cannot find method or property "Cookie.SetInt"
// D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(352) : error 105: cannot find method or property "Cookie.SetFloat"
//
// 6 Errors.
//
// Compilation Time: 1,37 sec
// ----------------------------------------

Is it possible to eliminate them in some way?

**Comment by Paimon-Kawaii** [comment]
> I was [informed of problems](https://ip-gamers.net/topic/2955-free-camera-for-fortnite-emotes-extension/#comment-12283) with compilation on SM 1.11.
> //// free_camera.sp
> //
> // D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(237) : error 105: cannot find method or property "Cookie.GetInt"
> // D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(238) : error 105: cannot find method or property "Cookie.GetInt"
> // D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(239) : error 105: cannot find method or property "Cookie.GetFloat"
> // D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(306) : error 105: cannot find method or property "Cookie.SetInt"
> // D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(316) : error 105: cannot find method or property "Cookie.SetInt"
> // D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(352) : error 105: cannot find method or property "Cookie.SetFloat"
> //
> // 6 Errors.
> //
> // Compilation Time: 1,37 sec
> // ----------------------------------------
> 
> Is it possible to eliminate them in some way?

In SM 1.11, these grammars didn't get support, so my suggestion is using SM 1.12 to compile it.

But if you need, you could fix them by following these:

at line 237:

``` pawn
g_bMenuHint[client] ​=​ ​view_as​<​bool​>​(g_hCameraCookies[CAMERA_HINT_ITEM].​GetInt​(client, ​1​));
```

should be replaced for:

``` pawn
char buffer[16];
g_hCameraCookies[CAMERA_HINT_ITEM].​Get​(client​, buffer, sizeof(buffer));
g_bMenuHint[client] ​=​ ​view_as​<​bool​>​(StringToInt(buffer)); 
```

for "GetInt" use "StringToInt", for "GetFloat" use "StringToFloat"

at line 306:

``` pawn
g_hCameraCookies[info].​SetInt​(client, g_bAutoCamera[client]); 
```

should be replaced for:

``` pawn
char buffer[16];
IntToString(g_bAutoCamera[client], buffer, sizeof(buffer));
g_hCameraCookies[info].​Set(client, buffer);
```

for "SetInt" use "IntToString", for "SetFloat" use "FloatToString"

**Comment by ryancoolround** [comment]
The plugin still refuses to compile.

**Comment by Paimon-Kawaii** [comment]
What did error report?

**Comment by Paimon-Kawaii** [comment]
What did error report?

**Comment by Paimon-Kawaii** [comment]
> The plugin still refuses to compile.

Please provide error messages.

**Comment by ryancoolround** [comment]
`// D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(240) : error 105: cannot find method or property "Cookie.GetInt"
// D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(241) : error 105: cannot find method or property "Cookie.GetFloat"
// D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(320) : error 105: cannot find method or property "Cookie.SetInt"
// D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(356) : error 105: cannot find method or property "Cookie.SetFloat"`

**Comment by Paimon-Kawaii** [comment]
> `// D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(240) : error 105: cannot find method or property "Cookie.GetInt"
> // D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(241) : error 105: cannot find method or property "Cookie.GetFloat"
> // D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(320) : error 105: cannot find method or property "Cookie.SetInt"
> // D:\Sourcemod\addons\sourcemod\scripting\free_camera.sp(356) : error 105: cannot find method or property "Cookie.SetFloat"`

These problems are the same as line 237 and line 306, so the way to slove them is also the same.

**Comment by Paimon-Kawaii** [comment]
If you want to translate the plugin to your language, just wait new version.
I have already add multilanguage support for new version, so that you won't need to compile it from then on.
You will be able to add your language at 'freecamera.phrases.txt' file.
