### ISSUE TITLE
HunterSkyCeil 插件的bug

### ISSUE THREAD

**Issue by NanakaFathry** [PaimonQwQ/L4D2-Plugins#7]
使用该插件并设置 hsc_human 为 1 后
人工的坦克左键也可以跟着原地起飞
![6adfbfc601547b265d8c2679e3e53626](https://github.com/Paimon-Kawaii/L4D2-Plugins/assets/108194610/25e8b83b-c73e-48eb-b6de-deb7700ee1cc)

**Comment by Paimon-Kawaii** [comment]
在[第175行](https://github.com/Paimon-Kawaii/L4D2-Plugins/blob/main/MyPlugins/HunterSkyCeil/hunter_skyceil.sp#L175)添加以下代码即可:
```c
if(g_bIsControllable[hunter] && (!IsInfected(hunter) || GetZombieClass(hunter) != ZC_Hunter))
    g_bIsControllable[hunter] = false;
```
