### ISSUE TITLE
關於SIPoolPlus 想請教

### ISSUE THREAD

**Issue by fbef0102** [PaimonQwQ/L4D2-Plugins#8]
您好，關於這插件想請教一些問題

https://forums.alliedmods.net/showthread.php?t=349615

看過說明書
知道特感bots死亡後會留在場上等待下次復活，就像對抗模式一樣
但我想問的是這些特感Bots如果一段時候沒有使用，會不會自動消失或踢出

譬如說多特插件會生成16個特感bots，依照這插件運作方式，有16個特感bots放在SI Pool等待復活
但後來多特插件只生成4個特感bots，那其他12個bots沒有使用會不會自動消失?
我擔心的只有這些bots會占用伺服器的位子 (server slots)

**Comment by Paimon-Kawaii** [comment]
> 知道特感bots死亡後會留在場上等待下次復活，就像對抗模式一樣
> 但我想問的是這些特感Bots如果一段時候沒有使用，會不會自動消失或踢出

> 譬如說多特插件會生成16個特感bots，依照這插件運作方式，有16個特感bots放在SI Pool等待復活
> 但後來多特插件只生成4個特感bots，那其他12個bots沒有使用會不會自動消失?
> 我擔心的只有這些bots會占用伺服器的位子 (server slots)

不会自动消失或踢出。如果有16个保留特感，但是只生成4个，剩余的12个不会消失，但是如果达到MaxSlots或者MaxClients，会选择踢出一个剩余最多的特感以保留空位；如果服务器有玩家进入，则SIPool会自动踢出一个死亡的特感Bot以留出足够的空位。

另外如果一局游戏结束，则所有保留的特感都会消失，这是由游戏引擎决定的，所以每局游戏开始都会重新预热。

**Comment by fbef0102** [comment]
Cool
